update websocket related packages version for avoiding conflict Issue description: When connect to django server, it shows following message TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'
this issue might cause by my channels version not support ASGI3
currently
reference:
https://github.com/django/channels/issues/1319